### ISSUE TITLE
Handle resizing

### ISSUE THREAD

**Issue by NickEntin** [dfed/Relativity#3]
Should the framework be able to handle sizing a view?  For instance, telling a view to fill up the space between 2 other views, with some amount of padding.

Per offline discussion with @dfed, this could be done using a separate set of operators, acting like "dragging" the edge of a view.  So you would place one side on one edge, and drag the other side to where it should be, and the width would be set accordingly.

**Comment by dfed** [comment]
Instead of providing a DSL for resizing, what if instead we provided a DSL for measuring distance? I imagine an API for measuring distance between two anchor points would be easier to understand than an API that required an anchor point and a size.

Imagine the following API:

```
public func |--|(lhs: ViewPosition, rhs: ViewPosition) -> CGSize
public func |--|(lhs: ViewPosition.Anchor, rhs: ViewPosition) -> CGSize
public func |--|(lhs: ViewPosition, rhs: ViewPosition.Anchor) -> CGSize
public func |--|(lhs: ViewPosition.OffsetAnchor, rhs: ViewPosition) -> CGSize
public func |--|(lhs: ViewPosition, rhs: ViewPosition.OffsetAnchor) -> CGSize
public func +(lhs: CGSize, rhs: UIOffset) -> CGSize
public func +(lhs: UIOffset, rhs: CGSize) -> CGSize
public func -(lhs: CGSize, rhs: UIOffset) -> CGSize
```

You could then size your views with: 
```
a.frame.size = a.topLeft |--| b.bottomLeft - 8.horizontalOffset
```
In this example, `a` is sized such that it takes up the space from it's top left anchor to the bottom left anchor of `b`, with 8 points of horizontal space between them.

**Comment by dfed** [comment]
I believe this has been addressed! Happy to re-open if you disagree :)
