### ISSUE TITLE
How to fill parent view?

### ISSUE THREAD

**Issue by gerchicov-vg** [dfed/Relativity#31]

**Comment by dfed** [comment]
You don't _need_ Relativity for this, but you can use it if you'd like:

```swift
subview.bounds = bounds
subview.middle --> middle
```

Without Relativity is just as easy:

```swift
subview.bounds = bounds
subview.center = center
```

**Comment by dfed** [comment]
It's worth noting that the above is an example of a parent view making a sub view fill itself, rather than making a sub view fill its parent view. I strongly recommend making parents size their children rather than making a view size itself.

Views that need specific sizing should implement `sizeThatFits`, and parent views should respect that. Parents should size and position children as they see fit. You generally speaking want to avoid children making sizing or positioning decisions relative to their parent view.

**Comment by NickEntin** [comment]
> ```swift
> subview.bounds = bounds
> subview.center = center
> ```

A couple caveats to this:

1. You probably want to set only the `subview.bounds.size`, not the entire bounds itself. For example, if your subview is a scroll view, setting the entire bounds would reset your content offset every time you have a layout pass.

2. This assume your views' layers have the same `anchorPoint`. The view's `center` is only actually its center point when its layer's anchor point is (0.5, 0.5). I'd guess this is true 99% of the time, but something to watch out for.
